//Console.WriteLine("Hello, World!");
//Var.MyVar();
//Var.DataType();
//SubStrings.MySubStrings();
//Math.Numbers();
//Input.Hello();
//Math.Add(100,450,12345);
//If.Numbers(-10);
//If.Health();
//Loops.ForLoops();
//Loops.EvenLoop();
//Loops.HealthLoop();
//Loops.WhileLoop();
// int result2 = Return1.PrintSquare(5);
// Console.WriteLine(result2);
//Return1.CheckEvenOdd(5);
// int result = Return1.AddNumber(3,6);
// Console.WriteLine(result);
//Loops.NestedLoops();
//Loops.dowhile();
//Character.Players();
Car.Drive("Ford",50);